### ISSUE TITLE
Project status 2020?

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [larsks/ansible-role#23]
Hey, 
I would first like to congratulate you on this project. 
It's aims to be everything I ever found missing in ansible...
It's often unclear to me how do people work and develop with ansible without the wrappers your project provides.

Now, having said that... Is the project bit rotting? :)
Did it continue to live somewhere else?

**Comment by larsks** [comment]
It's not "rotting". It's not getting any worse over time. It is, however, unmaintained.
